server:
  port: 8005
  servlet:
    context-path: /api/v1
spring:
  datasource:
    dbcp2:
      driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/test
    username: sa
    password: sa
    initialization-mode: never
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true